name: Deploy Staging

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build Dist Branch
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: "dist"
          fetch-depth: 0
      - uses: actions/setup-node@v1
        with:
          node-version: "12"
      - name: "set git bot commiter"
        run: git config --global user.name "KOH Build Bot" && git config --global user.email "bot@khouryofficehours.com"
      - name: "merge new changes into dist"
        run: git merge origin/master
      - uses: bahmutov/npm-install@v1
      - run: yarn build
      - name: Ensure latest commit
        id: isuptodate
        run: .github/scripts/isRepoUpToDate.sh
      - uses: EndBug/add-and-commit@v4
        if: steps.isuptodate.outputs.uptodate == "true"
        with:
          add: "packages"
          author_name: KOH Build Bot
          author_email: bot@khouryofficehours.com
          message: "Added built files"
          ref: "dist"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          name: id_rsa
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
      - uses: actions/checkout@v2
      - name: "pm2 deploy to staging"
        run: "npx pm2 deploy infrastructure/prod/ecosystem.config.js staging update"
