name: Lint and Typescript

on: pull_request

jobs:
  setup:
    name: setup
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        cmd:
          - "yarn pretty-quick --branch --check"
          - "yarn lint"
          - "yarn tsc"
    steps:
      - uses: actions/checkout@v2
      - name: install node v12
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: yarn install
      - run: ${{matrix.cmd}}
