name: Lint

on: pull_request

jobs:
  prettier:
    name: prettier
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install node v12
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: yarn install
      - run: yarn pretty-quick --branch --check
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install node v12
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: yarn install
      - run: yarn lint
  typescript:
    name: typescript
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install node v12
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: yarn install
      - run: yarn tsc
